# Generated by Django 3.0.3 on 2020-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('RegDate', models.DateField()),
                ('Adress', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
    ]
